---
title: "Housing-Foster_care"
author: "Julie Rebstock and JaiDa Robinson"
date: "6/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Housing Services/Programs in Loudoun County, VA 




## Housing Services/Programs in Allegheny County, PA 

### **FamilyLink Downtown Outreach Center & Shelter** [1] [2]

This program is contracted with DHS in Allegheny County to reserve 3 beds to provide emergency housing assistance and stabilization services to transition-age youth who may want to request that the courts resume jurisdiction or who are awaiting a court motion to place them in the care of child welfare. 

* Ages 18-24 with no permanent residence
* Provided with emergency shelter, food and clothing 
* Up to 60 days 
* Have the option of entering our Resumption Assistance Program, staying at DOCS for a period of time
* To enroll, must call the phone that is provided 

I found this document by going to Allegheny County's website and going to Youth and Family Support. Then all the way at the bottom, there is a link that downloads a document of the Allegheny County Youth Homelessness Demonstration Program from April 2020. Reading through this document, I searched key words like foster and then I saw they have a contract with FamilyLink and searched Family Link online. 


### **Permanent Supportive Housing for Transition Age Youth (TAY) program** [3] 

* Through Allegheny County's Housing as Home strategic plan
* Make 24 units available annually for Office of Behavioral Health (OBH) priority transition-age youth, with psychiatric disabilities
* Individuals are not required to participate in psychiatric services to keep their housing 
* Eligibility: 
  + Transitioning youth who lives in Allegheny County ages 18-25
  + Involved in or transitioning from other Department of Human Service system
  + Diagnosed with serious mental illness, mental illness and substance abuse
  + Desires to live independently
  
For More information, must call the number on this web page to get a referral through Community Care Behavioral Health Organization. 

I looked up "allegheny county housing programs transition age youth" and I clicked on the first option and all of this information came up. 
  
  
## **Action Housing MyPlace** [4] 

1. MyPlace Rapid Re-Housing: 
* young adults aged 18-24  
* Offers a stable living situation in which they can build their education and career skills
* Learn how to earn income, build personal and professional skills, and maintain their own permanent housing

2. MyPlace Permanent Supportive Housing 
* Provides stable housing for participants
* Allows to focus on obtaining/remaining in permanent housing, increasing income through stable employment, maximizing their ability to live independently and their quality of life

3. Foundation for Independence 
* Must be active with Allegheny County Department of Human Service’s Children Youth and Family (there is a link on the website to apply for by apart of CYF)
* Apply for an apartment with the recommendation of the CYF Caseworker
* Must have a high school diploma or GED and must be employed in order to be considered
* Involved in post-secondary education are required to work 20 hours per week 
* Not in post-secondary education are required to work 37.5 hours per week


There wasn't too much more information then what is above on how to apply and other requirements but there is contact information at the bottom for more information. I saw ActionHousing on KidsVoice website from when I was looking for education and employmeny programs so I don't think ActionHousing is super popular but if someone knew about the website, it was easy to navigate to what I was looking for. 



References: 

[1] “Downtown Outreach Center &amp; Shelter.” Familylinks, 5 Apr. 2016, familylinks.org/get-help/housing/DOCS. 

[2] “Allegheny County Youth Homelessness Demonstration Program.” Office of Community Services , Apr. 2020. 

[3] “Transition Age Youth (TAY).” Transitional Services, Inc., 21 Aug. 2017, www.transitionalservices.org/programs/psychiatric-disabilities/transition-age-youth-tay. 

[4] “MyPlace Youth Programs.” MyPlace Youth Program – Action Housing, actionhousing.org/our-services/myplace-youth-program/. 



