---
title: "Research-Foster_Care"
author: "Julie Rebstock and JaiDa Robinson"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Loudoun County, VA 

### Education 

### **Great Expectations** from Northern Viriginia Community College [8]

[website](https://www.nvcc.edu/acp/expectations.html)


* Connecting them to community resources, scholarship opportunities and other support
* Pursue an associate degree, get workforce training and/or transfer to a four-year college
* *Often free because of FAFSA, Grant programs and scholarship opportunities* 
* Referrals for tutorial services
* Participation in college trips and events
* Mentorship program with NOVA faculty/staff
* Eligibility: 
  + *17-24 year olds affiliated with the Virginia Foster Care System*
  + Youth adopted from the Virginia Foster Care System at the age of 13
* Has a link to find other local community colleges that have Great Expectation Programs 
* Cannot find which department 


**NOVA-Alexandria Campus** 

Engineering Building, AE 220 

5000 Dawes Ave., Alexandria, VA 22311


#### **Education and Training Voucher (ETV) Program** from Virginia Department of Social Services [1] 

[website](https://www.dss.virginia.gov/family/fc/etv.cgi)

* Assists eligible foster care and adopted teens or young adults with post-secondary education and training expenses
* Funds can be applied toward, but not limited to, colleges, universities, community colleges, vocational programs, and one-year training institution 
* *14 - 25 years of age*, hold a high school diploma or General Education Development (GED) certificate, enrolled or planning to enroll in a post-secondary education or vocational training program and must hold one of the below requirements 
    + *Currently in foster care or Fostering Futures*
    + *Have aged out of foster care or left Fostering Futures after turning 18*
    + *Have left foster care through adoption or the Kinship Guardianship Assistance Program after turning 16*
* Must maintain a 2.0 grade point average or make satisfactory progress

This is really just an application that provides funds for TAYs to go to school. The address below seems like their main office in Richmond. This program is one you have to call and ask about and depending on where you live, they will tell you the nearest center because it is open to all Virignia Residents who meet the requirements. 

**Address:**

801 E. Main Street, Richmond, VA 23219



#### **Independent Living Program ** [4]

[website](https://www.dss.virginia.gov/family/fc/independent.cgi)

  * *Virginia Department of Social Services* 
  * Goes along with ETV
  * assists foster care youths *ages 14-21* in developing the skills necessary to make the transition from foster care to independent living
  * include personal development skills such as self-esteem, communication skills, decision-making, conflict resolution and anger management
 * *Age 21 is the cut-off for services*
 * Must be a resident of Virginia
 * Acceptance is based on willingness of the youth to participate with services and expectations as documented in the “Resuming Independent Living Services Agreement”
* *One monthly contact with youth* 

**Same Address form above in Richmond** This program is one you have to call and ask about and depending on where you live, they will tell you the nearest center because it is open to all Virignia Residents who meet the requirements. 

#### Loudoun County Public School [3]

**Address of Coordinator:**

21000 Education Ct., Room 531, Ashburn, VA 20148


[website](https://www.lcps.org/Page/211221)

All of these programs and resources *are not directed towards Foster Care transitional aged youth* because there is no mention of any grant/scholarship that they could apply to for them to be paid for other than credit card.  

**Practical Nursing Program**

  * 2-year program; total cost : $6,100
  * First year 40-hour clinical experience at a long-term care facility
  * Second year 400-hour clinical component completed at a variety of health care settings including hospitals, physician offices, school and community clinics, and long-term care facilities 
  * Does not offer transportation to the clinical experiences
  * Must take TEAS exam ($65) 
  
*Location varies* 
  
  
**Adult High School **

  * 18 or older 
  * Designed for individuals who need between one (1) and ten (10) credits to complete their Standard High School Diploma requirements
  * Transcript from the last school attended must be presented prior to registration
  * Assigned independent work through the Credit Recovery Program but will be required to meet with instructors on a weekly basis
  * Tuition is $300 per course payable at time of registration by credit card 
  

**Park View High School**  

400 W. Laurel Avenue, Sterling VA 20164.
  
**English Learners (EL) - Aprenda Ingles**

  * Given in reading, writing, listening, and speaking
  * Classes meet twice a week - 13 weeks
  * MUST register and take a placement test prior
  * Must have access to smart phone and internet 
  * \$150.00 + \$20.00 Non-Refundable enrollment fee
    + Total = \$170.00
  * Have Daytime and Nighttime classes
    + 9AM-2PM or 6:30PM-8:30PM
    + **Daytime: 21000 Education Ct, Ashburn, VA 20148**
    + **Nightime: 21000 Education Ct, Ashburn, VA 20148 or 400 W Laurel Ave, Sterling, VA 20164 or 43460 Loudoun Reserve Dr, Ashburn, VA 20148** 
  * Website has this entire section in Spanish also 
  

**GED Prep School **

  * Offers preparatory classes provides basic skills instruction to adults whose math and reading skills have been assessed at or below the GED® readiness level 
  * Must meet with our staff members by phone/video, and attend our Informational Session prior 
  * Must taken placement test online with a proctor; this will assist with obtaining your academic progress to place you in the appropriate classes
  * Every session is $180
    + paid in full prior and only by credit card 
    
**All online because of COVID, so NO Address** 
    
    
**Adult Education Catalog **

  * Available to download from the website 
  * Lists all of the options from above with a little more detail
  * Additionally lists General Enrichment Courses 
    + All cost \$50 to \$200 
    
This is just a resource of all the classes someone can take. 

**Address:** 

21000 Education Ct, Ashburn, VA 20148


### Employment 

#### **Workforce Innovation and Opportunity Act Youth Program** [7] [9]

[Virginia Career Workers](https://vcwnorthern.com/youth-programs/)
[Loudoun County](https://www.loudoun.gov/2377/WIOA---Adult-and-Dislocated-Workers)

  * *US Department of Labor* 
  * *Services for 18-24* 
  * One on one assistance with a WIOA Case Manager
  * Access to career assessments
  * Career Coaching
  * Resume writing
  * Interview preparation
  * Job search assistance
  * Labor Market review
  * Access to education and training options
  * *Need IDs, past school records, Verification of Foster Care or receiving public assistance*
  
**Address:** 

102 Heritage Way, N.E., 1st Floor, Rear Entrance, Leesburg, VA 20176 

I accessed this by searching to Loudoun County Health and Human Services, going to Adult Services-Employment and Education. On this page, there is a link to Workforce Innovation / Opportunity Act Program where I found all of this information and has several links to the National page with videos and how to apply and how to get the applications. 
  
  

#### **Northern Virginia Educating Youth through Employment (EYE) ** [2]

[website](https://vcwnorthern.com/eye-programs/)

  * Summer initiative that recruits, screens and matches youth *ages 18-24* with professional opportunities in the private sector and other area businesses
  * Required to attend intensive training workshops before and during their work experience
  * Offers the youth an exciting, professional opportunity with training that will allow them to explore a career path that matches their interest
  * Jobs can include administrative assistant, electrician’s assistant, computer lab /IT
assistant, social media liaison, event planning assistant, among
many other pre-professional opportunities

This program can be anywhere because they set you up with different employers. The address below is the main office where the inital interaction begins.

**Address:**

8300 Boone Blvd., Suite 450, Vienna, VA 22182

This seems like a good program but I cannot seem to find the requirements for this or how to apply as a young adult. There are not materials or links that provide additional information than what is above which is mostly just general information. 


**Virginia Initiative for Education and Work (VIEW)** [6]

[website](https://www.loudoun.gov/1597/VIEW-Vehicles-for-Change)

* offers case management and support services to Loudoun County residents who are or have been, within the last 12 months, recipients of TANF (Temporary Assistance for Needy Families) 
* Crisis Intervention
* Educational Opportunities
* Job Search Support
* Training
* Transportation
* *Must be a TANF recipient* 

 
The TANF program provides eligible families with a monthly cash payment to meet their basic needs. For a child to be eligible he must be: [5]

* Under age 18, or if 18, will graduate from high school before age 19
* Going to school regularly if he is between the ages of five and 18
* Living with a parent or other relative
* A U.S. citizen or an eligible immigrant

For more information, this is the main building in Loudoun. 

**Shenandoah Building** 

102 Heritage Way, NE, Suite 103, Leesburg, VA 20176
  
  
### References: 

[1] “Education and Training Voucher (ETV) Program.” Education and Training Voucher (ETV) Program - Virginia Department of Social Services, www.dss.virginia.gov/family/fc/etv.cgi. 

[2] “EYE Program.” Virginia Career Works Northern Region, 17 Feb. 2021, vcwnorthern.com/eye-programs/. 

[3] “Instructional Programs / Adult Education.” Loudoun County Public Schools, 2021, www.lcps.org/Page/211221.

[4] “Services for Older Youth.” Services for Older Youth - Virginia Department of Social Services, 2021, www.dss.virginia.gov/family/fc/independent.cgi. 

[5] “Temporary Assistance for Needy Families (TANF).” Temporary Assistance for Needy Families (TANF) - Virginia Department of Social Services, Commonwealth of Viriginia, 2017, www.dss.virginia.gov/benefit/tanf/. 

[6] “VIEW / Vehicles for Change.” VIEW / Vehicles for Change | Loudoun County, VA - Official Website, CivicPlus, www.loudoun.gov/1597/VIEW-Vehicles-for-Change. 

[7] Virginia Career Works Northern Region, 2021, vcwnorthern.com/youth-programs.

[8] “Welcome to the Northern Virginia Community College Website.” Great Expectations - Northern Virginia Community College, 2021, www.nvcc.edu/acp/expectations.html. 

[9] “Workforce Innovation / Opportunity Act Program (WIOA).” Workforce Innovation / Opportunity Act Program (WIOA) | Loudoun County, VA - Official Website, 2021, www.loudoun.gov/2377/WIOA---Adult-and-Dislocated-Workers. 



  
## Housing Services/Programs
  
#### **Housing Choice Voucher Program "Formerly Section 8"** [2]

[website](https://www.loudoun.gov/1816/Housing-Choice-Voucher-Program)

  * Have household income at or below 50 percent of the area median income $142,000.
  * Be a United States citizen, or a non-citizen with eligible immigration status.
  * Candidates must apply and will be placed on waiting list that becomes open. 
  * The county provides public notification of openings through local newspaper and the website.
  * The candidate can apply to multiple waiting list.
  * Does not offer security deposits, no rent sharing, and the candidate applying is responsible for finding their own housing with assistance.


#### **Affordable Dwelling Unit Program** [1]

[website](https://www.loudoun.gov/1813/Affordable-Dwelling-Unit-Program)

  * This program provides newly constructed, affordable units for rent and sell for income-eligible citizen who live and work in the county.
  * Sessions are provided to help with the process of applying and the application but attendance is not required to apply.
  * Citizens must apply online and in person 10 days after online submission. The processor with take 2-3 weeks through through email.
  
  
  
### References:

[1] “Affordable Dwelling Unit Program.” Affordable Dwelling Unit Program | Loudoun County, VA - Official Website, www.loudoun.gov/1813/Affordable-Dwelling-Unit-Program. 

[2] “Housing Choice Voucher Program (Formerly Section 8).” Housing Choice Voucher Program (Formerly Section 8) | Loudoun County, VA - Official Website, www.loudoun.gov/1816/Housing-Choice-Voucher-Program. 

## Transportation 

#### **Route 54 (Safe T-ride)** [1]

[website](https://www.loudoun.gov/3302/Local-Bus)
[pdf](https://www.loudoun.gov/DocumentCenter/View/122385/TDP-2018-2028-?bidId=)

* Free for all in the county; not specific to foster care youths 
* Weekdays: 7AM-7PM
* Weekends: 9AM-6PM 
* Every 20 minutes, max 30 minutes 
* 10 stops; 3 shopping centers 

There is a map of this bus's route at the bottom of the PDF, but also you can go to Department of Transportation and Capital Infrastructure for more information. 

**Department of Transportation and Capital Infrastructure**

101 Blue Seal Dr, Suite 102, Leesburg, VA 20175

#### **Medicaid Transportation (LogistiCare) ** [2]

[website](http://transportation.dmas.virginia.gov/ ) 
[pdf](https://www.loudoun.gov/DocumentCenter/View/54405/Public--Private-Transportation-Providers?bidId=)

* Must have Medicaid number
* Non-emergency and urgent medical appointments 
* Make trip request at least 5 days in advance unless urgent appointment 
* Provided by Department of Medical Assistance Services (DMAS)

Must call to make an appointment. There is no specific place to go to to make an appointment and can take you anywhere for non-emergency appointments only with a 5 days request. 

**Administrative Office**

7443 Lee Davis Road, 2nd Floor, Suite 200, Mechanicsville, VA 23111

#### **On Demand Transportation** [2]

[website](https://www.loudoun.gov/1699/On-Demand-Transportation)
[pdf](https://www.loudoun.gov/DocumentCenter/View/54405/Public--Private-Transportation-Providers?bidId=)

* Department of Family Services 
* Vendors: Yellow Cab 
* Must schedule ahead of time 
* Fall below 70% of State's Median Income 
* Referrals are required from government agencies as well as non-profits 
* Majority used are eldery and disabled because this is usually the last resort 
* Locally, to UVA, and Georgetown Hospital 

Requests are made through Department of Family Services, Department of Mental Health, Substance Abuse, and Developmental Services, the Health Department or a private human services agency by a services worker (Medicaid) mainly through phone or email. 

**Family Services** 

Shenandoah Building

102 Heritage Way, NE, Suite 103, Leesburg, VA 20176

**MHSADS **

102 Heritage Way, NE, Suite 302, Leesburg, VA 20176

**Health Department Administrative Office **

1 Harrison Street, SE, 2nd Floor, Leesburg, VA 20175

**Health Clinic **

102 Heritage Way NE, Suites 100 & 101, Leesburg, VA 20176




### References: 

[1] County Staff . (2018, January 10). Loudoun County Transit Development Plan. TranSystem . 

[2] Public &amp; Private Transportation Providers Serving Loudoun County. (2021, February). 


### Insurances 

#### **Family Access to Medical Insurance Security Plan** [1] 

[website](https://www.coverva.org/en/famis)
[pdf](https://www.coverva.org/sites/default/files/2021-05/FAMIS-brochure-English-FINAL-020121.pdf)

* covers all the medical care that growing children need to stay healthy and if they get sick or hurt 
* no enrollment costs or monthly premiums; no copays 
* May qualify if: 
  + Live in Virginia
  + Are uninsured
  + Are under age 19
  + Are U.S. citizens or lawfully residing immigrants
  + Live in families that meet income rules 
* For 1 family size, (ex. 18 year old) income must be below \$2,201 monthly or \$26,404 yearly 

There are extra links at the bottom for more information and a link on where to apply and who to call if someone needs help. I found this on the Loudoun County website under Needs & Assistance and Apply for. Then click Medicaid but the link under this page takes you to an invalid page but teh website is Cover Virginia where you can click on Learn and our Programs. 
 


#### **Virginia Medicaid** [2]

[website](https://www.coverva.org/en/adults-19-64-years-old)

* Ages 18 to 26 can get Medicaid if they were in foster care and had Medicaid in any state on their 18th birthday
* No income limit for this program
* Still must apply through link on site 

I found this the same way I found the above program also. They are on the same website. 

The address below is for more information and details on FAMIS and Medicaid in which you need to make an appointment first. 

**Inova Partnership for Healthier Kids**

211 Gibson St. NW, Suite 206, Leesburg VA 20176


### References: 

[1] Maximus Digital Solutions. (2021). FAMIS. https://www.coverva.org/en/famis. 

[2] Maximus Digital Solutions. (2021). Adults 19-64 years old. https://www.coverva.org/en/adults-19-64-years-old. 


### Policy and Funding 

**Continuum of Care (CoC) ** [1] 

[website](https://www.loudoun.gov/4111/Continuum-of-Care-Programs-Partnerships)

* US Department of Housing and Urban Development 
* Awarded vouchers to provide stable housing for young adults (18-24) who have aged out of the foster care system 
* To provide funding for efforts by nonprofit providers, States, and local governments to quickly re-house homeless individuals, families, persons fleeing domestic violence, and youth

#### **SkillSource Group Inc. ** [3]

[website](https://vcwnorthern.com/about/)

* Serves as fiscal agent
* An entity that pursues additional funding sources for the board of Workforce Innovation and Opportunity Training and Employment programs 


#### **Educational and Training Vouchers (ETVs)** [2] 

[website](https://www.dss.virginia.gov/family/fc/etv.cgi)


* Funded by Virginia Department of Social Services through the US Federal Government 
* To provide financial assistance of up to $5,000 per year for up to five years for college, career school, or training 


#### **Community College Tuition Grant** [4]

[pdf](https://www.vccs.edu/wp-content/uploads/2020/04/FINANCIAL-AID-PROGRAMS-revised-100719.pdf)

* assists community college students in Virginia with financial need 
* Lots of grants that are included and can be applied for 
* All of these assist any student in Virginia, not specific to foster care transition age youths 


#### Funding for all Transition Aged Youth in US 

[website](https://www.cwla.org/child-trends-report-on-funding-supports-and-services-for-transition-age-youth/)

**Title IV-E Foster Care** 

* supports youth under the age of 18, room and board, and other costs reimbursed to the state

**Title IV-E reimbursement**

* States can choose to enable this 
* Extends foster care to age 21

**ACA, Medicaid, Family Unification Program (FUP), Workforce Innovation and Opportunity Act, and TRIO programs that support the needs of older youth**

* ACA extended Medicaid eligibility to young adults to age 26
* FUP program provides housing choice vouchers for youth transitioning from foster care


References: 

[1] CivicPlus . (n.d.). Continuum of Care Programs &amp; Partnerships. Continuum of Care Programs &amp; Partnerships | Loudoun County, VA - Official Website.
https://www.loudoun.gov/4111/Continuum-of-Care-Programs-Partnerships. 

[2] “Education and Training Voucher (ETV) Program.” Education and Training Voucher (ETV) Program - Virginia Department of Social Services, www.dss.virginia.gov/family/fc/etv.cgi.

[3] SkillsSource. (2021, June 15). About Us. Virginia Career Works Northern Region. https://vcwnorthern.com/about/. 

[4] Virginia's Community Colleges . (2020, April). FINANCIAL AID PROGRAMS AVAILABLE AT VIRGINIA’S COMMUNITY COLLEGES. 



---
---

## Allegheny County, PA 

In 2006, oversight of all transition programs was placed under the Department of Human Services Office which emphasizes on youth involvement and engaging youth in services. [2]

### Education 

#### **412 Youth Zone Program** [1]

[website](https://www.alleghenycounty.us/Human-Services/Programs-Services/Teens-Young-Adults/412-Youth-Zone.aspx)

* *Department of Human Services* 
* One-stop drop-in center for young people *ages 16-23* that are transitioning out of the foster care system
* Are eligible for independent living services or are experiencing unstable housing
* Contains kitchen and common area for meals, playroom, laundry room, offices and classrooms 
* Services included: 

  + Life skills assessments
  + Individualized goal plans
  + Job and career development
  + Personal safety and health 
  + Career development and job skills
  + Financial assistance
  + Employment assistance
  + Housing, household and dormitory items
  
**Address:** 

Wood Street Commons, 304 Wood Street, Sixth Floor, Pittsburgh, PA 15222

I found this page that has all of this information plus contact information and hours that this program is open by going to alleghenycounty.us, Department of Human Services and searching transition age youth. This was the 4th option down. 
  


### Employment 

#### **The Independent Living Initiative** [3]

[website](https://www.alleghenycounty.us/WorkArea/linkit.aspx?LinkIdentifier=id&ItemID=2147493264)

* Individuals age 14-24 who have had experience in foster care for at least 30 days after their 14th birthday
* Enhanced services for *18-24 year olds* that focus on 

  + Career development and job skills
  + Assistance in finances 
  + Assistance in employment, housing and household items 
  + **Funded by Blending Funding** (Chaffee & State Funds) which eliminates waiting lists 
  
From 2008-2009, 32% of the youth using Independent Living Programs 16-21 were pregnant of parenting so in response DHS now sponsors parenting programs for all youths in the program. 

* Partners with *Kidsvoice* in which they co-sponsor a career /college fair for post 18 youths. 

**Address:**

1 Smithfield Street, Suite 200, Pittsburgh, PA 15222


When I searched Allegheny County, PA Transition Age Youth, this was the first link and it automatically downloaded a PDF to my computer with a presentation with all of this information. I did not like this because it was hard for me to know where this information was coming from and to find out more about what they were talking about. 


#### **Auberle’s Employment Institute** [2]

[website](https://www.auberle.org/employment-institute)

* University of Pittsburgh Medical Center (UPMC) POWRR (Partnership on Workforce Readiness and Retention) community partner
* Offers special classes to help prepare individuals to be hired by UPMC
* Program Offerings: 

  + Career Pathways: 
  
    - Provides *young adults (ages 16-24)* with the skills needed to find employment and build a pathway to a successful career
    - Cannot be enrolled in GED program or High school 
    - *Must be facing barriers to employment, such as parenting, low-income, involvement in Justice System, or unemployed* 
    
* Services: Job readiness training, counseling, GED completion, work experience, education support and tutoring/mentorship, food pantry access, College/Trade School Application Assistance and Tours, Work Attire and Safety Equipment

**Address:** 

1101 Hartman Street, McKeesport, PA 15132


I found KidsVoice because of the presentation from above so there was not real link from the Allegheny County site. If I hadn't seen KidsVoice on the presentation from above, I would probably not know any of this exists. But the KidsVoice website has a lot of good information and you can search which area you need help with, I selected TAYs and Independent Living and this and the program below showed up and then it links you to some presentations and brochures and other sites with good information with contact information. 


### References: 

[1] “412 Youth Zone.” Teens and Young Adults | 412 Youth Zone | Allegheny County, 2021, www.alleghenycounty.us/Human-Services/Programs-Services/Teens-Young-Adults/412-Youth-Zone.aspx. 

[2] “Employment Institute at Auberle.” Auberle, 2021, www.auberle.org/employment-institute. 

[3] “Transition Age Youth in Allegheny County.” Allegheny County, Department of Human Services , 2016. 



### Housing Services/Programs

#### **FamilyLink Downtown Outreach Center & Shelter** [1] [2]

[website](https://familylinks.org/get-help/housing/DOCS)
[pdf](https://www.alleghenycounty.us/Human-Services/News-Events/Accomplishments/Youth-and-Family-Support/Allegheny-County-YHDP-Coordinated-Community-Plan.aspx)

This program is contracted with DHS in Allegheny County to reserve 3 beds to provide emergency housing assistance and stabilization services to transition-age youth who may want to request that the courts resume jurisdiction or who are awaiting a court motion to place them in the care of child welfare. 

* Ages 18-24 with no permanent residence
* Provided with emergency shelter, food and clothing 
* Up to 60 days 
* Have the option of entering our Resumption Assistance Program, staying at DOCS for a period of time
* To enroll, must call the phone that is provided 

**Address:** 

601 Fifth Ave, Pittsburgh, PA 15219

I found this document by going to Allegheny County's website and going to Youth and Family Support. Then all the way at the bottom, there is a link that downloads a document of the Allegheny County Youth Homelessness Demonstration Program from April 2020. Reading through this document, I searched key words like foster and then I saw they have a contract with FamilyLink and searched Family Link online. 


#### **Permanent Supportive Housing for Transition Age Youth (TAY) program** [4] 

[website](https://www.transitionalservices.org/programs/psychiatric-disabilities/transition-age-youth-tay)

* Through Allegheny County's Housing as Home strategic plan
* Make 24 units available annually for Office of Behavioral Health (OBH) priority transition-age youth, with psychiatric disabilities
* Individuals are not required to participate in psychiatric services to keep their housing 
* Eligibility: 
  + Transitioning youth who lives in Allegheny County ages 18-25
  + Involved in or transitioning from other Department of Human Service system
  + Diagnosed with serious mental illness, mental illness and substance abuse
  + Desires to live independently
  
For More information, must call the number on this web page to get a referral through Community Care Behavioral Health Organization. There is no address available. 

I looked up "allegheny county housing programs transition age youth" and I clicked on the first option and all of this information came up. 

Address: 615 Island Ave, McKees Rocks, PA 15136

Address: 5231 Penn Ave, Pittsburgh, PA 15224

Address: 5700 Bryant St # 11, Pittsburgh, PA 15206

Address: 362 S Highland Ave, Pittsburgh, PA 15206

Address: 806 West St, Homestead, PA 15120

Address: 215 S Braddock Ave, Pittsburgh, PA 15221

  
#### **Action Housing MyPlace** [3] 

[website](https://actionhousing.org/our-services/myplace-youth-program/)

**Supportive Housing Management Services (SHMS)**

803 East Pittsburgh Plaza

East Pittsburgh, PA 15112


1. MyPlace Rapid Re-Housing: 
* young adults aged 18-24  
* Offers a stable living situation in which they can build their education and career skills
* Learn how to earn income, build personal and professional skills, and maintain their own permanent housing

2. MyPlace Permanent Supportive Housing 
* Provides stable housing for participants
* Allows to focus on obtaining/remaining in permanent housing, increasing income through stable employment, maximizing their ability to live independently and their quality of life

3. Foundation for Independence 
* Must be active with Allegheny County Department of Human Service’s Children Youth and Family (there is a link on the website to apply for by apart of CYF)
* Apply for an apartment with the recommendation of the CYF Caseworker
* Must have a high school diploma or GED and must be employed in order to be considered
* Involved in post-secondary education are required to work 20 hours per week 
* Not in post-secondary education are required to work 37.5 hours per week


There wasn't too much more information then what is above on how to apply and other requirements but there is contact information at the bottom for more information. I saw ActionHousing on KidsVoice website from when I was looking for education and employmeny programs so I don't think ActionHousing is super popular but if someone knew about the website, it was easy to navigate to what I was looking for. 



### References: 

[1] “Allegheny County Youth Homelessness Demonstration Program.” Office of Community Services , Apr. 2020. 

[12 “Downtown Outreach Center &amp; Shelter.” Familylinks, 5 Apr. 2016, familylinks.org/get-help/housing/DOCS. 

[4] “MyPlace Youth Programs.” MyPlace Youth Program – Action Housing, actionhousing.org/our-services/myplace-youth-program/. 

[3] “Transition Age Youth (TAY).” Transitional Services, Inc., 21 Aug. 2017, www.transitionalservices.org/programs/psychiatric-disabilities/transition-age-youth-tay. 

  


### Transportation 

#### **Self Sufficiency Programs** [3] 

[website](https://www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Self-Sufficiency-Case-Management,-Training,-and-Job-Placement.aspx)

* This program has services that are for the TAY if they would have roadblocks keeping them from getting ahead or earn less than what they need to live. The services would help the TAY figure out their strengths and weakness, create a plan to reach their goals, and connect to those resources to help them achieve their goals. 
* Eligibility: 
  + Allegheny County resident
  + Live in a household whose total income is no more than 200% of the federal Income Poverty Guidelines
  + Are at least 18 years old
  + Desires to live independently
  

#### **Behavioral Health Transportation Program:** [1] 

[website](https://www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Transportation/Behavioral-Health-Transportation-Program.aspx)

* Through Allegheny County's Housing as Home strategic plan
* Make 24 units available annually for Office of Behavioral Health (OBH) priority transition-age youth, with psychiatric disabilities
* Individuals are not required to participate in psychiatric services to keep their housing 
* Eligibility: 
  + Be receiving behavioral health services from a BHTP-participating, Department of Human services (DHS)- contracted provider. 
  + Live in Allegheny County
  + Live at least one-half mile from an eligible destination AND 
  + Start attending at least three eligible trips per week as stated in service plan. An eligible trip is any trip you need to take as part of your personal recovery journey: dinner with a friend or family; a trip to the grocery store; AA or NA. Anything that’s in your plan can count as an eligible trip.
  
  + You do NOT need to be on Medical Assistance to enroll. 


#### **Medical Assistance Transportation Program** [2] 

[website](https://www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Transportation/Medical-Assistance-Transportation-Program.aspx)

* This program provides: 
  + Free public transportation (bus, subway and incline) ahead-of-time ticket,
  + Reimbursement for your use of public transportation or a private car, 
  + and Free door-to-door service, when medically necessary, via shared-ride or ride-hailing service. 

* Eligibility: 
  + You are eligible for Medicaid
  + You are a resident of Alleghany County
  
 
### References: 

[1] “Behavioral Health Transportation Program.” Transportation | Behavioral Health | Allegheny County, www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Transportation/Behavioral-Health-Transportation-Program.aspx. 

[2] “Medical Assistance Transportation Program.” Transportation | Medical Assistance Transportation Program | Allegheny County, www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Transportation/Medical-Assistance-Transportation-Program.aspx.

[3] “Self-Sufficiency Programs.” Employment, Self Sufficiency Case Management, Training, and Job Placement,  Allegheny County, www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Self-Sufficiency-Case-Management,-Training,-and-Job-Placement.aspx. 


### Insurances 

#### **Health Insurance Options** [1] 

[website](https://www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Health-Insurance.aspx)

1. Health Insurance Marketplace: 
*  [website](https://www.healthcare.gov/)


2. Alleghany Activates 
* Has information about the Affordable Care Act and how to choose a plan that is right for you. 


3. Medical Assistance (Medicaid) “MA”: 
* Provides free health care coverage to low-income Pennsylvania residents. Residents should fit into one of the eligibility groups that are covered by the program and have income, and sometimes resources, which fall below the level set by the state for their category of MA eligibility.   
* Apply using the COMPASS website, or by calling the County Assistance Office at 412-565-2146.


4. Behavioral Health Insurance (mental health, alcohol, drug, or other addiction services)
* Community Behavioral Health Organization (community Care) is the behavioral health managed care organization for Allegheny County residents who receive Medical Assistance.


5. Mental Health Rx Pharmacy Benefit Program
* Providing psychiatric prescription medications at no cost to eligible individuals. Eligibility is based on income. 


There wasn't too much more information then what is above on how to apply and other requirements but there is contact information at the bottom for more information. 


###References

[1] “Health Insurance.” Basic Needs, Health Insurance, Allegheny County, www.alleghenycounty.us/Human-Services/Programs-Services/Basic-Needs/Health-Insurance.aspx. 

### Policy and Funding 

**This will be almost exactly the same as Loudoun County because most of the programs and services are funded from the federal government or the state government. ** 
  

  
  
  
  
