---
title: "Demographics-Juvenile_Detention-Code"
author: "Austin Burcham and Kyle Jacobs"
date: "6/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/austi/Documents/VT DSPG/Loudoun/Excel Files")
```

## R Markdown
```{r, Lououn Racial Demographics of Intakes}
intake_race <- read.csv(file = "C:\\Users\\austi\\Documents\\VT DSPG\\Loudoun\\Excel Files\\DJJ-2020-Juvenile_Detention_Locality-Race_Intake.csv", header = T)
intake_race_FY2020 <- intake_race$FY20..
loudoun_intake_race_FY2020 <- intake_race_FY2020[285:288]
barplot(height = loudoun_intake_race_FY2020, names.arg = c("Asian", "Black", "White", "Other/Unlisted"), col = "coral", ylim = c(0,0.8), xlab = "Race", ylab = "Relative Frequency", 
        main = "Racial Demographics of Loudoun Intakes")
pie(loudoun_intake_race_FY2020, labels = c("Asian", "Black", "White", "Other/Unlisted"), main = "Racial Demographics of Loudoun Intakes")
```

```{r, Loudoun Ethnicity}
intake_ethnicity <- read.csv(file = "C:\\Users\\austi\\Documents\\VT DSPG\\Loudoun\\Excel Files\\DJJ-2020-Juvenile_Detention_Locality-Ethnicity_Intake.csv", header = TRUE)
intake_ethnicity_FY2020 <- intake_ethnicity$FY20..
loudoun_intake_ethnicity_FY2020 <- intake_ethnicity_FY2020[214:216]
barplot(height = loudoun_intake_ethnicity_FY2020, names = c("Hispanic", "Non-Hispanic", "Unkown/Missing"), col = "darkseagreen2", xlab = "Ethnicity", 
        main = "Ethnic Demographics of Loudoun Intakes", 
        ylab = "Relative Frequency", ylim = c(0, 0.8))
pie(loudoun_intake_ethnicity_FY2020, labels = c("Hispanic", "Non-Hispanic", "Unkown/Missing"), main = "Ethnic Demographics of Loudoun Intakes")
```

```{r, Loudoun Age}
intake_age <- read.csv("C:\\Users\\austi\\Documents\\VT DSPG\\Loudoun\\Excel Files\\DJJ-2020-Juvenile_Detention_Locality-Age_Intake.csv")
intake_age_2020 <- intake_age$FY20..
loudoun_intake_age_FY2020 <- intake_age_2020[640:647]
ages <- c("8-12", "13", "14", "15", "16", "17", "18-20", "Missing")
barplot(height = loudoun_intake_age_FY2020, names.arg = ages, col = "brown1", xlab = "Age", 
        main = "Age Demographics of Loudoun Intakes", 
        ylab = "Relative Frequency", ylim = c(0, 0.35))
pie(loudoun_intake_age_FY2020, labels = ages, main = "Age Demographics of Loudoun Intakes" )
```

```{r, Juvenile Intake Sex}
intake_sex <- read.csv("C:\\Users\\austi\\Documents\\VT DSPG\\Loudoun\\Excel Files\\DJJ-2020-Juvenile_Detention_Locality-Sex_Intake.csv")
intake_sex_2020 <- intake_sex$FY20..
loudoun_intake_sex_FY2020 <- intake_sex_2020[143:144]
sex <- c("Female", "Male")
barplot(height = loudoun_intake_sex_FY2020, names.arg = sex, col = c("darkslategray2", "firebrick2"), xlab = "Sex", 
        main = "Sex Demographics of Loudoun Intakes", 
        ylab = "Relative Frequency", ylim = c(0, 0.9))
pie(loudoun_intake_sex_FY2020, labels = sex, main = "Sex Demographics of Loudoun Intakes")
```





